services:
  wallos:
    container_name: wallos
    image: bellamy/wallos:latest
    ports:
      - "8282:80"      
    environment:
      TZ: 'Asia/Ho_Chi_Minh'  
    volumes:
      - ./db:/var/www/html/db               
    restart: unless-stopped